# Health Stats Part 4: Pandas DataFrames

<!--- Paste in your explanation from part 1.  --->
The Waist-Hip Ratio is defined by using the variables W for weight and H for height. This ratio shows the relationship between the circumfrence of the waist and the hips. This is calculated by dividing W by H (W/H=WHR).

## Source Data

<!--- Paste in your data definition table from part 2. --->
- ID : Identifiaction number for each user.
- Waist : Waist value (inches) for each user.
- Hips : Hip value (inches) for each user.
- Gender : Gender for each user (M or F).

## Data Import

In [4]:
# Goal: Extract the data from the file
# import pandas as pd & numpy as np
import numpy as np
import pandas as pd

# import W2h_data.csv file and check data types are assigned correctly
rows = pd.read_csv('w2h_data.csv',dtype={"ID":np.int64, "Waist":np.float64,"Hip": np.float64, "Gender":np.str})
#rows.head()
rows.dtypes

ID          int64
Waist     float64
Hip       float64
Gender     object
dtype: object

## Calculations

In [5]:
# Goal: For each row of data calculate and store the w2h_ratio and shape.

# calculate the waist to hips ratios
w2h_ratios = rows['Waist']/rows['Hip']

# determine who is male (True) or female (False)
males = (rows['Gender']=='M')

# males with w2h ration > 0.9 are apple shaped
male_apples = np.logical_and((w2h_ratios>0.9),males)

# females with w2h ratio > 0.8 are apple shaped
female_apples = np.logical_and((w2h_ratios>0.8),np.logical_not(males))

# combines the male_apples and female_apples
apples=np.logical_or(male_apples,female_apples)

# works like an if then else statement
shapes=np.where(apples,'Apple','Pear')

# The code below creates a new results array 
    
# add the two new columns
rows['W2H Ratio']=w2h_ratios
rows['Shape']=shapes
rows

# convert to dataframe and delete ID column
bmi = pd.DataFrame(rows, index=rows.ID -1)
del bmi['ID']
bmi

    Waist   Hip Gender  W2H Ratio  Shape
ID
0    30.0  32.0      M   0.937500  Apple
1    32.0  37.0      M   0.864865   Pear
2    30.0  36.0      M   0.833333   Pear
3    33.0  39.0      M   0.846154   Pear
4    29.0  33.0      M   0.878788   Pear
5    32.0  38.0      M   0.842105   Pear
6    33.0  42.0      M   0.785714   Pear
7    30.0  40.0      M   0.750000   Pear
8    30.0  37.0      M   0.810811   Pear
9    32.0  39.0      M   0.820513   Pear
10   24.0  35.0      F   0.685714   Pear
11   25.0  37.0      F   0.675676   Pear
12   24.0  37.0      F   0.648649   Pear
13   22.0  34.0      F   0.647059   Pear
14   26.0  38.0      F   0.684211   Pear
15   26.0  37.0      F   0.702703   Pear
16   25.0  38.0      F   0.657895   Pear
17   26.0  37.0      F   0.702703   Pear
18   28.0  40.0      F   0.700000   Pear
19   23.0  35.0      F   0.657143   Pear

## Output

In [6]:
# Goal: pretty print the rows as an HTML table

# Convert to HTML table
bmi.to_html("bmi.html")

# Export to a CSV called "StatsResults.csv"
bmi.to_csv("StatsResults.csv")